///////////////////////////////////////////////////////////////////////////////
// RobotModuleClassFactory.cpp
#include "TcPch.h"
#pragma hdrstop

#include "RobotModuleClassFactory.h"
#include "RobotModuleServices.h"
#include "RobotModuleVersion.h"
#include "Robot.h"

BEGIN_CLASS_MAP(CRobotModuleClassFactory)
///<AutoGeneratedContent id="ClassMap">
	CLASS_ENTRY(CID_RobotModuleCRobot, SRVNAME_ROBOTMODULE "!CRobot", CRobot)
///</AutoGeneratedContent>
END_CLASS_MAP()

CRobotModuleClassFactory::CRobotModuleClassFactory() : CObjClassFactory()
{
	TcDbgUnitSetImageName(TCDBG_UNIT_IMAGE_NAME(SRVNAME_ROBOTMODULE)); 
#if defined(TCDBG_UNIT_VERSION)
	TcDbgUnitSetVersion(TCDBG_UNIT_VERSION(RobotModule));
#endif //defined(TCDBG_UNIT_VERSION)
}

