///////////////////////////////////////////////////////////////////////////////
// Robot.h
#pragma once
#include "GeneralRobot/GeneralRobot.h"
#include "RobotModuleInterfaces.h"

class CRobot 
	: public ITComObject
	, public ITcADI
	, public ITcWatchSource
///<AutoGeneratedContent id="InheritanceList">
	, public IRobot
///</AutoGeneratedContent>
{
public:
	DECLARE_IUNKNOWN()
	DECLARE_IPERSIST(CID_RobotModuleCRobot)
	DECLARE_ITCOMOBJECT_LOCKOP()
	DECLARE_ITCADI()
	DECLARE_ITCWATCHSOURCE()
	DECLARE_OBJPARAWATCH_MAP()
	DECLARE_OBJDATAAREA_MAP()

	CRobot();
	virtual	~CRobot();

///<AutoGeneratedContent id="InterfaceMembers">
	// IRobot
	virtual ULONG TCOMAPI InitRobot(st_InitParameter* pInitPar);
	virtual ULONG TCOMAPI RunRobot(st_AxisGroupRead* pMC_Inputs, st_AxisGroupSet* pMC_Outputs, Recvbuff* pCtlComd, Sendbuff* pRobotStatus);
	virtual HRESULT TCOMAPI StopRobot();

///</AutoGeneratedContent>

protected:
	DECLARE_ITCOMOBJECT_SETSTATE();

///<AutoGeneratedContent id="Members">
///</AutoGeneratedContent>


///=========================================================
	CGeneralRobot robot;

};
