///////////////////////////////////////////////////////////////////////////////
// RobotModuleServices.h

#pragma once

#include "TcServices.h"


typedef long long DINT;
const ULONG DrvID_RobotModule = 0x3F000000;
#define SRVNAME_ROBOTMODULE "RobotModule"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_RobotModuleCRobot = {0xe3cbe668,0x9044,0x452b,{0xa1,0xaa,0xd1,0x22,0xd6,0x72,0xd9,0x22}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#if !defined(_TC_TYPE_3DD5BF5D_CAE2_4B02_853C_7823514EBE54_INCLUDED_)
#define _TC_TYPE_3DD5BF5D_CAE2_4B02_853C_7823514EBE54_INCLUDED_
enum eMC_Motion : LONG {
	eMC_NONE = 0,
	eMC_RESET = 1,
	eMC_HOME = 2,
	eMC_POWER = 3,
	eMC_STOP = 4,
	eMC_HALT = 5,
	eMC_MOV_ABS = 6,
	eMC_MOV_CON_ABS = 7,
	eMC_MOV_RELATIVE = 9,
	eMC_MOV_VEL = 10
};
#endif // !defined(_TC_TYPE_3DD5BF5D_CAE2_4B02_853C_7823514EBE54_INCLUDED_)

#if !defined(_TC_TYPE_ECD7093D_84B1_4DCE_8FD3_5FECA3911656_INCLUDED_)
#define _TC_TYPE_ECD7093D_84B1_4DCE_8FD3_5FECA3911656_INCLUDED_
enum eAxis_States : LONG {
	eAxis_UNDEFINED = 0,
	eAxis_DISABLED = 1,
	eAxis_STANDSTILL = 2,
	eAxis_ERRORSTOP = 3,
	eAxis_STOPPING = 4,
	eAxis_HOMING = 5,
	eAxis_DISCRETEMOTION = 6,
	eAxis_CONTINOUSMOTION = 7,
	eAxis_SYNCHRONIZEDMOTION = 8
};
#endif // !defined(_TC_TYPE_ECD7093D_84B1_4DCE_8FD3_5FECA3911656_INCLUDED_)

#if !defined(_TC_TYPE_9C054410_FD15_4319_843A_82C59CC2246D_INCLUDED_)
#define _TC_TYPE_9C054410_FD15_4319_843A_82C59CC2246D_INCLUDED_
typedef struct _st_SetAxis
{
	ULONG Index;
	eMC_Motion eMC_Motion;
	bool bEnable;
	unsigned char reserved1[7];
	double Position;
	double Velocity;
	double Torque;
	double EndVelocity;
	double Distance;
} st_SetAxis, *Pst_SetAxis;
#endif // !defined(_TC_TYPE_9C054410_FD15_4319_843A_82C59CC2246D_INCLUDED_)

#if !defined(_TC_TYPE_6E6455FB_F847_4761_AF0F_6D621F0AA3E4_INCLUDED_)
#define _TC_TYPE_6E6455FB_F847_4761_AF0F_6D621F0AA3E4_INCLUDED_
typedef struct _st_ReadAxis
{
	ULONG Index;
	eAxis_States eState;
	double Position;
	double Velocity;
	double Torque;
	double Current;
	double Acceleration;
	ULONG ErrorID;
	bool Error;
	bool bHomed;
	unsigned char reserved1[2];
} st_ReadAxis, *Pst_ReadAxis;
#endif // !defined(_TC_TYPE_6E6455FB_F847_4761_AF0F_6D621F0AA3E4_INCLUDED_)

#if !defined(_TC_TYPE_B98167E8_0DA1_4964_97FB_04A3E4FC85D8_INCLUDED_)
#define _TC_TYPE_B98167E8_0DA1_4964_97FB_04A3E4FC85D8_INCLUDED_
typedef struct _stAction
{
	bool bflag[16];
	ULONG iData[16];
	double dData[16];
} stAction, *PstAction;
#endif // !defined(_TC_TYPE_B98167E8_0DA1_4964_97FB_04A3E4FC85D8_INCLUDED_)

#if !defined(_TC_TYPE_67A85B2E_3D03_448A_92A9_2AA4E9750A65_INCLUDED_)
#define _TC_TYPE_67A85B2E_3D03_448A_92A9_2AA4E9750A65_INCLUDED_
typedef struct _st_AxisGroupSet
{
	ULONG Number;
	unsigned char reserved1[4];
	st_SetAxis AxisGroup[20];
	stAction RobotSetAction;
	stAction LinkSetActions[6];
} st_AxisGroupSet, *Pst_AxisGroupSet;
#endif // !defined(_TC_TYPE_67A85B2E_3D03_448A_92A9_2AA4E9750A65_INCLUDED_)

#if !defined(_TC_TYPE_2795DE3B_85A3_4575_B002_5B15DEF32B9C_INCLUDED_)
#define _TC_TYPE_2795DE3B_85A3_4575_B002_5B15DEF32B9C_INCLUDED_
typedef struct _st_AxisGroupRead
{
	ULONG Number;
	unsigned char reserved1[4];
	st_ReadAxis AxisGoup[20];
	stAction RobotActAction;
	stAction LinkActActions[6];
} st_AxisGroupRead, *Pst_AxisGroupRead;
#endif // !defined(_TC_TYPE_2795DE3B_85A3_4575_B002_5B15DEF32B9C_INCLUDED_)

#if !defined(_TC_TYPE_D725118C_E845_4968_A17E_442AB4535B6C_INCLUDED_)
#define _TC_TYPE_D725118C_E845_4968_A17E_442AB4535B6C_INCLUDED_
typedef BYTE Recvbuff[3000];
#endif // !defined(_TC_TYPE_D725118C_E845_4968_A17E_442AB4535B6C_INCLUDED_)

#if !defined(_TC_TYPE_99F04275_81C5_4CC3_A499_173A200C8B79_INCLUDED_)
#define _TC_TYPE_99F04275_81C5_4CC3_A499_173A200C8B79_INCLUDED_
typedef BYTE Sendbuff[3000];
#endif // !defined(_TC_TYPE_99F04275_81C5_4CC3_A499_173A200C8B79_INCLUDED_)

#if !defined(_TC_TYPE_8BDE3EF9_CD9A_4F17_857D_FC11A5DF2CAE_INCLUDED_)
#define _TC_TYPE_8BDE3EF9_CD9A_4F17_857D_FC11A5DF2CAE_INCLUDED_
enum eConfigMode : ULONG {
	eNone = 0,
	eInit = 1,
	eHomed = 2
};
#endif // !defined(_TC_TYPE_8BDE3EF9_CD9A_4F17_857D_FC11A5DF2CAE_INCLUDED_)

#if !defined(_TC_TYPE_193F32A1_4268_4405_8082_179ACDDBAE73_INCLUDED_)
#define _TC_TYPE_193F32A1_4268_4405_8082_179ACDDBAE73_INCLUDED_
typedef struct _st_InitParameter
{
	ULONG JointsNum;
	ULONG RecvSize;
	ULONG SendSize;
} st_InitParameter, *Pst_InitParameter;
#endif // !defined(_TC_TYPE_193F32A1_4268_4405_8082_179ACDDBAE73_INCLUDED_)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="InterfaceIDs">
#if !defined(_TC_IID_4F1720B0_73ED_4CFA_A4FA_F4D2622882F0_INCLUDED_)
#define _TC_IID_4F1720B0_73ED_4CFA_A4FA_F4D2622882F0_INCLUDED_
TCOM_DECL_INTERFACE("4f1720b0-73ed-4cfa-a4fa-f4d2622882f0", IRobot)
#endif // !defined(_TC_IID_4F1720B0_73ED_4CFA_A4FA_F4D2622882F0_INCLUDED_)

///</AutoGeneratedContent>
