///////////////////////////////////////////////////////////////////////////////
// Robot.cpp
#include "TcPch.h"
#pragma hdrstop

#include "Robot.h"

#ifdef _DEBUG
#define new DEBUG_NEW
#endif
DEFINE_THIS_FILE()

///////////////////////////////////////////////////////////////////////////////
// Collection of interfaces implemented by module CRobot
BEGIN_INTERFACE_MAP(CRobot)
	INTERFACE_ENTRY_ITCOMOBJECT()
	INTERFACE_ENTRY(IID_ITcADI, ITcADI)
	INTERFACE_ENTRY(IID_ITcWatchSource, ITcWatchSource)
///<AutoGeneratedContent id="InterfaceMap">
	INTERFACE_ENTRY(IID_IRobot, IRobot)
///</AutoGeneratedContent>
END_INTERFACE_MAP()

IMPLEMENT_ITCOMOBJECT(CRobot)
IMPLEMENT_ITCOMOBJECT_SETSTATE_LOCKOP2(CRobot)
IMPLEMENT_ITCADI(CRobot)
IMPLEMENT_ITCWATCHSOURCE(CRobot)

///////////////////////////////////////////////////////////////////////////////
// Set parameters of CRobot 
BEGIN_SETOBJPARA_MAP(CRobot)
	SETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="SetObjectParameterMap">
///</AutoGeneratedContent>
END_SETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get parameters of CRobot 
BEGIN_GETOBJPARA_MAP(CRobot)
	GETOBJPARA_DATAAREA_MAP()
///<AutoGeneratedContent id="GetObjectParameterMap">
///</AutoGeneratedContent>
END_GETOBJPARA_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get watch entries of CRobot
BEGIN_OBJPARAWATCH_MAP(CRobot)
	OBJPARAWATCH_DATAAREA_MAP()
///<AutoGeneratedContent id="ObjectParameterWatchMap">
///</AutoGeneratedContent>
END_OBJPARAWATCH_MAP()

///////////////////////////////////////////////////////////////////////////////
// Get data area members of CRobot
BEGIN_OBJDATAAREA_MAP(CRobot)
///<AutoGeneratedContent id="ObjectDataAreaMap">
///</AutoGeneratedContent>
END_OBJDATAAREA_MAP()


///////////////////////////////////////////////////////////////////////////////
// Constructor
CRobot::CRobot()
{
///<AutoGeneratedContent id="MemberInitialization">
///</AutoGeneratedContent>
}

///////////////////////////////////////////////////////////////////////////////
// Destructor
CRobot::~CRobot() 
{
}

///////////////////////////////////////////////////////////////////////////////
// State Transitions 
///////////////////////////////////////////////////////////////////////////////
IMPLEMENT_ITCOMOBJECT_SETOBJSTATE_IP_PI(CRobot)

///////////////////////////////////////////////////////////////////////////////
// State transition from PREOP to SAFEOP
//
// Initialize input parameters 
// Allocate memory
HRESULT CRobot::SetObjStatePS(PTComInitDataHdr pInitData)
{
	HRESULT hr = S_OK;
	IMPLEMENT_ITCOMOBJECT_EVALUATE_INITDATA(pInitData);
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to OP
//
// Register with other TwinCAT objects
HRESULT CRobot::SetObjStateSO()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from OP to SAFEOP
HRESULT CRobot::SetObjStateOS()
{
	HRESULT hr = S_OK;
	return hr;
}

///////////////////////////////////////////////////////////////////////////////
// State transition from SAFEOP to PREOP
HRESULT CRobot::SetObjStateSP()
{
	HRESULT hr = S_OK;
	return hr;
}

///<AutoGeneratedContent id="ImplementationOf_IRobot">
ULONG CRobot::InitRobot(st_InitParameter* pInitPar)
{
	ULONG result;
	result = robot.Init(pInitPar);
	return result;
}

ULONG CRobot::RunRobot(st_AxisGroupRead* pMC_Inputs, st_AxisGroupSet* pMC_Outputs, Recvbuff* pCtlComd, Sendbuff* pRobotStatus)
{
	ULONG result;
	robot.Run(pMC_Inputs, pMC_Outputs, pCtlComd, pRobotStatus);
	return 0;
}

HRESULT CRobot::StopRobot()
{
	HRESULT hr = S_OK;

	return hr;
}
///</AutoGeneratedContent>

///<AutoGeneratedContent id="Obsolete_ImplementationOf_IRobot">
//
//ULONG CRobot::InitRobot()
//{
//	ULONG result;
//	result = robot.RobotInit();
//	return 10;
//}
//
///</AutoGeneratedContent>

///<AutoGeneratedContent id="Obsolete_ImplementationOf_IRobot">
//
//ULONG CRobot::RunRobot(AxisGroupRead* pMC_Inputs, AxisGroupSet* pMC_Outputs, Recvbuff* pCtlComd, Sendbuff* pRobotStatus)
//{
//	ULONG result = 0;
//	robot.RobotRun(pMC_Inputs, pMC_Outputs, pCtlComd, pRobotStatus);
//	return result;
//}
//
///</AutoGeneratedContent>

///<AutoGeneratedContent id="Obsolete_ImplementationOf_IRobot">
//
//ULONG CRobot::RunRobot(AxisGroupRead* Inputs, AxisGroupSet* Outputs, stCommand* Commd, stStatus* Status)
//{
//	ULONG result;
//	result = robot.RobotRun(Inputs, Outputs, Commd, Status);
//	return result;
//}
//
///</AutoGeneratedContent>

///<AutoGeneratedContent id="Obsolete_ImplementationOf_IRobot">
//
//HRESULT CRobot::InitRobot()
//{
//	HRESULT hr = S_OK;
//	robot.RobotInit();	
//	return hr;
//}
//
//
//HRESULT CRobot::RunRobot(AxisGroupRead* Inputs, AxisGroupSet* Outputs, stCommand* Commd, stStatus* Status)
//{
//	HRESULT hr = E_NOTIMPL;
//	robot.RobotRun(Inputs,Outputs,Commd,Status);
//	return hr;
//}
//
///</AutoGeneratedContent>



