///////////////////////////////////////////////////////////////////////////////
// RobotModuleInterfaces.h

#pragma once

#include "TcInterfaces.h"
#include "TcIoInterfaces.h"
#include "TcRtInterfaces.h"
#include "RobotModuleServices.h"

///<AutoGeneratedContent id="Interfaces">
#if !defined(_TC_TYPE_4F1720B0_73ED_4CFA_A4FA_F4D2622882F0_INCLUDED_)
#define _TC_TYPE_4F1720B0_73ED_4CFA_A4FA_F4D2622882F0_INCLUDED_
struct __declspec(novtable) IRobot : public ITcUnknown
{
	virtual ULONG TCOMAPI InitRobot(st_InitParameter* pInitPar)=0;
	virtual ULONG TCOMAPI RunRobot(st_AxisGroupRead* pMC_Inputs, st_AxisGroupSet* pMC_Outputs, Recvbuff* pCtlComd, Sendbuff* pRobotStatus)=0;
	virtual HRESULT TCOMAPI StopRobot()=0;
};
_TCOM_SMARTPTR_TYPEDEF(IRobot, IID_IRobot);
#endif // !defined(_TC_TYPE_4F1720B0_73ED_4CFA_A4FA_F4D2622882F0_INCLUDED_)

///</AutoGeneratedContent>
